# Generated by Django 5.2.9 on 2025-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_recovery_answer_user_recovery_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='strike_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
